export const SAMPLE_ACTION = "SAMPLE_ACTION";

export const NOTIFY_START = "NOTIFY_START";
export const NOTIFY_STOP = "NOTIFY_STOP";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CLEAR_ERROR = "AUTH_CLEAR_ERROR";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const CROPS_FETCH_START = "CROPS_FETCH_START";
export const CROPS_FETCH_SUCCESS = "CROPS_FETCH_SUCCESS";
export const CROPS_FETCH_FAIL = "CROPS_FETCH_FAIL";